services:
  - type: web
    name: your-backend-name
    runtime: python3.9
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn main:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
